### ISSUE TITLE
Tests for angular sleep module (pending Protractor setup)

### ISSUE THREAD

**Issue by aisapatino** [TrackYourself/track-yourself#12]
- [x] unit tests
- [ ] integration tests

**Comment by ChelseaLura** [comment]
I split up your sleep tests into integration and unit tests. I also split up Back-end vs front-end testing sense they have different frameworks and requirements. Your back-end sleep integration tests run great, however I had trouble with the unit test.

I spent a long time trying to get a couple of plug-ins working that would mock our mongoose db. I found out they were all a bit too out of date with the virtual method mongoose and none of them worked properly. :(

We can talk to Ivan/ Tyler about seeing if there are others ways to mock the model dependencies.

(I tried: Mockgoose & MongooseMock)

**Comment by aisapatino** [comment]
Hm, did you try running the unit tests with `mongod` running?  That's how I was doing it and it worked.  I had set up a separate testing db.

Edit: I tried it out and it needs not only mongod running, but to actually connect to the database.  I required the server file at the top and the tests pass.

I'd be curious what they say about mocking vs using mongoose itself.  At some point it feels like we'd be testing the mocks rather than emulating our actual setup.

**Comment by aisapatino** [comment]
I asked Tyler about this and got some clarification:
- He said when testing backend models, validation, etc. he recommends using mongoose/mongod itself
- For frontend tests, he'd recommend using a simple mock that we create ourselves.  I.e. we would make a test version of `app/modules/sleep/services.js` that just returns an object rather than actually hitting the backend.  The idea is to have as few dependencies as possible.

**Comment by ChelseaLura** [comment]
Protractor on hold for now

**Comment by aisapatino** [comment]
I'm closing this for now; it's lacking in front-end integration tests but the most important one (the form) is there. And the other tests should make sure that data can be fetched.
