### ISSUE TITLE
Add front-end integration testing with Protractor

### ISSUE THREAD

**Issue by ChelseaLura** [TrackYourself/track-yourself#13]

**Comment by ChelseaLura** [comment]
On hold for now, will come back to this branch soon.

**Comment by aisapatino** [comment]
I found the existing sleep tests really helpful when working on auth, so I've been wanting to write front-end integration tests.  I started a branch off of yours and you were really close, I was able to get protractor working with a few small tweaks.  Gonna try to get a test passing and I'll do a pull request.

**Comment by aisapatino** [comment]
Fixed in #48
