### ISSUE TITLE
Water module

### ISSUE THREAD

**Issue by aisapatino** [TrackYourself/track-yourself#17]
Track water intake
- [ ] backend
  - [ ] mongoose schema & model
  - [ ] express routes for REST API
  - [ ] unit tests
- [ ] angular module
  - [ ] controller(s)
  - [ ] template(s)
  - [ ] $resource service to connect to backend
  - [ ] unit tests
  - [ ] integration tests

**Comment by joshcanhelp** [comment]
Dupe of #21
