### ISSUE TITLE
Exercise module

### ISSUE THREAD

**Issue by aisapatino** [TrackYourself/track-yourself#18]
@ChelseaLura Can't remember which module you said you wanted to do, so you can edit the issue just wanted to make issues for all the stuff we talked about today.
- [ ] backend
  - [x] mongoose schema & model
  - [x] express routes for REST API
  - [ ] unit tests
- [ ] angular module
  - [x] controller(s)
  - [x] template(s)
  - [x] $resource service to connect to backend
  - [ ] unit tests
  - [ ] integration tests

**Comment by ChelseaLura** [comment]
Thanks for setting up the check boxes, you are the best! :)

**Comment by aisapatino** [comment]
@ChelseaLura this one is finished, right?

**Comment by ChelseaLura** [comment]
I wanted to add front-end tests; however outside of that it is done. Wasn't certain if I should close issue until I had finished the tests
