### ISSUE TITLE
Finalize auth

### ISSUE THREAD

**Issue by aisapatino** [TrackYourself/track-yourself#19]
After talking to Tyler, we don't need to use jwtAuth tokens.  Just get passport set up with REST API
- [x] remove jwt code and verify that login & register still work
- [x] add auth to base angular page
- [x] add auth to api
- [x] write auth tests
  - [x] register works, logs in automatically, redirects to dashboard (/app for now)
  - [x] login works and redirects to dashboard (/app for now)
  - [x] can access public pages while logged out (home, login, register,)
  - [x] cannot access private pages while logged out (angular, api)

**Comment by ChelseaLura** [comment]
Sweet!

**Comment by aisapatino** [comment]
Closed with #25
