### ISSUE TITLE
Switch Express rendering to use Jade

### ISSUE THREAD

**Issue by joshcanhelp** [TrackYourself/track-yourself#20]
Send instructions to Liz on where files are, how to process.

**Comment by aisapatino** [comment]
FYI this is what I had posted in gitter earlier

> templates:
> for pages where a user is not logged in (register, login, home page) put in views/
> for pages where a user is logged in (dashboard, input page, etc) put in app/modules/core/templates/

**Comment by joshcanhelp** [comment]
@LizJohnston I switched the templating to Jade and translated all the existing templates over. Works great, I really like Jade so far! Everything is in /views and should be fairly straightforward. Let me know if you have any questions.

**Comment by aisapatino** [comment]
@joshcanhelp I just updated my master branch and when I try to load a page after starting the local server I get an error. I did `npm install` and `bower install` first.

```
Error: Cannot find module 'jade'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at new View (/home/aisa/Projects/codefellows/tracker/node_modules/express/lib/view.js:43:49)
    at Function.app.render (/home/aisa/Projects/codefellows/tracker/node_modules/express/lib/application.js:501:12)
```

**Comment by joshcanhelp** [comment]
Oh ... I'm not sure. I found this:

http://stackoverflow.com/a/17848670/728480

... and this:

https://www.openshift.com/forums/express/nodejs-and-jade-error-cannot-find-module-jade

... on the Googles. Sounds like maybe I have Jade installed globally?  Yup:

https://www.dropbox.com/s/v3tvh2fohohwpxr/Screenshot%202014-06-20%2007.30.43.png

Added it to the packaged and committed. Sorry for the trouble!

---

_Josh "can help" Cunningham_
joshcanhelp.com http://www.joshcanhelp.com
@joshcanhelp http://twitter.com/joshcanhelp

**Comment by aisapatino** [comment]
Thanks!  Tried it out and it's working :)
