### ISSUE TITLE
Add "water" module based on Aisa's existing module

### ISSUE THREAD

**Issue by joshcanhelp** [TrackYourself/track-yourself#21]

**Comment by joshcanhelp** [comment]
I've got add and all working. Last doesn't seem to be pulling the right thing so that needs a look.

**Comment by aisapatino** [comment]
It looks like this is using the old code from the sleep module before I updated it to handle users.  So it will only create/find things for a fake user with the id of 'testuser'.

Could also use some tests.  The unit tests I did seemed kind of pointless, but integration ones have been useful.

**Comment by joshcanhelp** [comment]
Word.

Forgot about the tests, I'll add those this afternoon and take a look at
the user handling.

---

_Josh "can help" Cunningham_
joshcanhelp.com http://www.joshcanhelp.com
@joshcanhelp http://twitter.com/joshcanhelp
