### ISSUE TITLE
Redirect logged-in users from Login + Register to profile

### ISSUE THREAD

**Issue by joshcanhelp** [TrackYourself/track-yourself#23]

**Comment by aisapatino** [comment]
I'm working on this as part of getting auth integrated with angular.  I was thinking it could be dashboard instead of profile? Or did we want a profile page that's separate from the account settings page?

**Comment by joshcanhelp** [comment]
Dashboard is fine with me. Profile/settings don't need to be separate at
this point, IMHO.

On Thursday, June 19, 2014, Anna Luisa Patiño West notifications@github.com
wrote:

> I'm working on this as part of getting auth integrated with angular. I was
> thinking it could be dashboard instead of profile? Or did we want a profile
> page that's separate from the account settings page?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TrackYourself/track-yourself/issues/23#issuecomment-46581818
> .

## 

---

_Josh "can help" Cunningham_
joshcanhelp.com http://www.joshcanhelp.com
@joshcanhelp http://twitter.com/joshcanhelp

**Comment by aisapatino** [comment]
Closing - part of #19
