### ISSUE TITLE
Update login and register templates

### ISSUE THREAD

**Issue by aisapatino** [TrackYourself/track-yourself#50]
Put inside some container so they're not 100% width.

**Comment by LizJohnston** [comment]
I will also confirm the wording in register is "Sign Up."

**Comment by LizJohnston** [comment]
Created div container to limit login and sign up to 25% wide. Added margin to put more towards the center of the page. Played with additional styling ideas with a background color for these forms and a border. Updated register.jade text to say "Sign Up."
