### ISSUE TITLE
Fix bottom whitespace

### ISSUE THREAD

**Issue by aisapatino** [TrackYourself/track-yourself#55]
Min-width on container or fill in the bottom part

**Comment by LizJohnston** [comment]
After all the page views are completed, look to see if add a min-height is required to fill in any white space. Could also consider giving the html tag the same color assignment as the header and footer tags.

**Comment by LizJohnston** [comment]
Implemented possible fix of giving the html the same background color as the footer (darker blue). May also consider min-height in the future, depending on team feedback.

**Comment by LizJohnston** [comment]
Happy with fix, so closing issue.
