### ISSUE TITLE
Buggy auth

### ISSUE THREAD

**Issue by aisapatino** [TrackYourself/track-yourself#65]
Sometimes doesn't redirect when it should -- need to fix the paths it checks against.

**Comment by aisapatino** [comment]
Should be fixed

**Comment by aisapatino** [comment]
Buggy again - `/#home` and even `/`redirect to login

Write tests this time.

**Comment by LizJohnston** [comment]
If I refresh my screen, it logs me out.

**Comment by aisapatino** [comment]
@LizJohnston See #59.  We could try to check for cookies, which I think is a better solution, but we probably don't have time to check that by tomorrow.
