### ISSUE TITLE
Build the homepage

### ISSUE THREAD

**Issue by joshcanhelp** [TrackYourself/track-yourself#67]
- Slider with example graphs
- Testimonials 
- Intro content

**Comment by aisapatino** [comment]
I got the placeholder version up. If you go to `localhost:3000` is should redirect to `localhost:3000/#/home`

Oh, and the template is in `app/modules/core/templates/home.html`

**Comment by LizJohnston** [comment]
I am helping.

**Comment by joshcanhelp** [comment]
Assigning to Liz for completion
