### ISSUE TITLE
Style links

### ISSUE THREAD

**Issue by aisapatino** [TrackYourself/track-yourself#69]
Non-default colors

**Comment by LizJohnston** [comment]
Which links need styling?
I had originally set all the text links as the same blue as the header and footer areas. I need some more information to address this issue.

**Comment by aisapatino** [comment]
All `<a>` elements like we talked about earlier.  Not sure if you did that already, I just saw that links were blue (unvisited) and purple (visited) when I ran the server just now.

**Comment by LizJohnston** [comment]
Updated the a tag styling to apply to all a tags. This should correct this issue.
