### ISSUE TITLE
Consistent navigation

### ISSUE THREAD

**Issue by aisapatino** [TrackYourself/track-yourself#70]
When logged out, should be able to access:
- home
- _login_
- _sign up_

When logged in:
- dashboard
  - _dashboard links to indiv modules_
    - those modules should show links to dashboard/forms
- _logout button_
- forms/input page

Issue is mainly figuring out how to do some kind of selective angular nesting or show/hiding

**Comment by LizJohnston** [comment]
If it's not already set up already, we can link the logo by placing the <a> tag around the <figure> tag. I choose the figure tag because it will be least likely to affect the styling.
