### ISSUE TITLE
Style sub-navigation

### ISSUE THREAD

**Issue by aisapatino** [TrackYourself/track-yourself#71]
I think it could use some styling to make it not blend in with the other text.  If you end up having time.  Looks like this right now:
![subnav](https://cloud.githubusercontent.com/assets/1279315/3394518/b01f5f02-fce2-11e3-9d7e-9aed0197f383.png)

I figured out how to add a class if the link corresponds to the current page, in case we want to style them differently to indicate that.  Right now it's set so that the dashboard link has the class "active" if you're currently on the dashboard, and same for the forms link.  (I can change that class name if you want).

**Comment by LizJohnston** [comment]
As tested, a links are now appearing as desired both in nav and other links.
